server:
  port: 8083

spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/budgetdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

transaction:
  service:
    url: http://transaction-service:8082
notification:
  service:
    url: http://notification-service:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info